# Docker

# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: abnamro-assignment-CI

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  azureSubscription: "<your-azure-subscription-name>"
  azureContainerRegistry: "<your-azure-container-registry-id>"
  dockerComposeFile: "**/docker-compose.yml"
  tag: "$(Build.BuildId)"

stages:
  - stage: BuildAndTest
    jobs:
      - job: Frontend
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSource: "spec"
              versionSpec: "18.x"

          - task: Npm@1
            displayName: "Frontend - Install dependencies"
            inputs:
              command: "ci"
              workingDir: "frontend"

          - task: Npm@1
            displayName: "Frontend - Run tests"
            inputs:
              command: "custom"
              workingDir: "frontend"
              customCommand: "run test:unit"

          - task: Npm@1
            displayName: "Frontend - Build"
            inputs:
              command: "custom"
              workingDir: "frontend"
              customCommand: "run build"

      - job: Backend
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSource: "spec"
              versionSpec: "18.x"

          - task: Npm@1
            displayName: "Backend - Install dependencies"
            inputs:
              command: "ci"
              workingDir: "backend"

          - task: Npm@1
            displayName: "Backend - Run tests"
            inputs:
              command: "custom"
              workingDir: "backend"
              customCommand: "test"

  - stage: BuildAndPushContainers
    dependsOn: BuildAndTest
    condition: succeeded()
    jobs:
      - job: DockerBuildPush
        steps:
          - task: DockerCompose@1
            displayName: "Docker compose build"
            inputs:
              containerregistrytype: "Azure Container Registry"
              azureSubscription: "$(azureSubscription)"
              azureContainerRegistry: "$(azureContainerRegistry)"
              dockerComposeFile: "$(dockerComposeFile)"
              projectName: "abnamro-assignment"
              action: "Build services"
              additionalImageTags: |
                $(tag)
                latest
                dev

          - task: DockerCompose@1
            displayName: "Docker compose push"
            inputs:
              containerregistrytype: "Azure Container Registry"
              azureSubscription: "$(azureSubscription)"
              azureContainerRegistry: "$(azureContainerRegistry)"
              dockerComposeFile: "$(dockerComposeFile)"
              projectName: "abnamro-assignment"
              action: "Push services"
              additionalImageTags: |
                $(tag)
                latest
                dev

  - stage: Deploy
    dependsOn: BuildAndPushContainers
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: DeployToAzure
        steps:
          - task: AzureWebAppContainer@1
            displayName: "Deploy Backend Container"
            inputs:
              azureSubscription: "$(azureSubscription)"
              appName: "abnamro-assignment-backend"
              containers: "$(azureContainerRegistry)/backend:$(tag)"

          - task: AzureWebAppContainer@1
            displayName: "Deploy Frontend Container"
            inputs:
              azureSubscription: "$(azureSubscription)"
              appName: "abnamro-assignment-frontend"
              containers: "$(azureContainerRegistry)/frontend:$(tag)"
